//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDMConfig.AuthenticateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://throwdownplanner.com/", ConfigurationName="AuthenticateService.authenticate_ServicesSoap")]
    public interface authenticate_ServicesSoap {
        
        // CODEGEN: Generating message contract since element name login_name from namespace http://throwdownplanner.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/SignIn", ReplyAction="*")]
        RDMConfig.AuthenticateService.SignInResponse SignIn(RDMConfig.AuthenticateService.SignInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/SSO", ReplyAction="*")]
        void SSO();
        
        // CODEGEN: Generating message contract since element name email from namespace http://throwdownplanner.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/ADLookup", ReplyAction="*")]
        RDMConfig.AuthenticateService.ADLookupResponse ADLookup(RDMConfig.AuthenticateService.ADLookupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/SignOut", ReplyAction="*")]
        void SignOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/BrowserClosed", ReplyAction="*")]
        void BrowserClosed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/KeepSessionAlive", ReplyAction="*")]
        void KeepSessionAlive();
        
        // CODEGEN: Generating message contract since element name login_name from namespace http://throwdownplanner.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/TemporaryPassword", ReplyAction="*")]
        RDMConfig.AuthenticateService.TemporaryPasswordResponse TemporaryPassword(RDMConfig.AuthenticateService.TemporaryPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name user_id from namespace http://throwdownplanner.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/UpdatePassword", ReplyAction="*")]
        RDMConfig.AuthenticateService.UpdatePasswordResponse UpdatePassword(RDMConfig.AuthenticateService.UpdatePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name login_name from namespace http://throwdownplanner.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/SupportSignIn", ReplyAction="*")]
        RDMConfig.AuthenticateService.SupportSignInResponse SupportSignIn(RDMConfig.AuthenticateService.SupportSignInRequest request);
        
        // CODEGEN: Generating message contract since element name login_name from namespace http://throwdownplanner.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/LinkSite", ReplyAction="*")]
        RDMConfig.AuthenticateService.LinkSiteResponse LinkSite(RDMConfig.AuthenticateService.LinkSiteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignIn", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.SignInRequestBody Body;
        
        public SignInRequest() {
        }
        
        public SignInRequest(RDMConfig.AuthenticateService.SignInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class SignInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SignInRequestBody() {
        }
        
        public SignInRequestBody(string login_name, string password) {
            this.login_name = login_name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInResponse", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.SignInResponseBody Body;
        
        public SignInResponse() {
        }
        
        public SignInResponse(RDMConfig.AuthenticateService.SignInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SignInResponseBody {
        
        public SignInResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADLookupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADLookup", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.ADLookupRequestBody Body;
        
        public ADLookupRequest() {
        }
        
        public ADLookupRequest(RDMConfig.AuthenticateService.ADLookupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class ADLookupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public ADLookupRequestBody() {
        }
        
        public ADLookupRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADLookupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADLookupResponse", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.ADLookupResponseBody Body;
        
        public ADLookupResponse() {
        }
        
        public ADLookupResponse(RDMConfig.AuthenticateService.ADLookupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ADLookupResponseBody {
        
        public ADLookupResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TemporaryPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TemporaryPassword", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.TemporaryPasswordRequestBody Body;
        
        public TemporaryPasswordRequest() {
        }
        
        public TemporaryPasswordRequest(RDMConfig.AuthenticateService.TemporaryPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class TemporaryPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login_name;
        
        public TemporaryPasswordRequestBody() {
        }
        
        public TemporaryPasswordRequestBody(string login_name) {
            this.login_name = login_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TemporaryPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TemporaryPasswordResponse", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.TemporaryPasswordResponseBody Body;
        
        public TemporaryPasswordResponse() {
        }
        
        public TemporaryPasswordResponse(RDMConfig.AuthenticateService.TemporaryPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TemporaryPasswordResponseBody {
        
        public TemporaryPasswordResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePassword", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.UpdatePasswordRequestBody Body;
        
        public UpdatePasswordRequest() {
        }
        
        public UpdatePasswordRequest(RDMConfig.AuthenticateService.UpdatePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class UpdatePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public UpdatePasswordRequestBody() {
        }
        
        public UpdatePasswordRequestBody(string user_id, string password) {
            this.user_id = user_id;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePasswordResponse", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.UpdatePasswordResponseBody Body;
        
        public UpdatePasswordResponse() {
        }
        
        public UpdatePasswordResponse(RDMConfig.AuthenticateService.UpdatePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdatePasswordResponseBody {
        
        public UpdatePasswordResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SupportSignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SupportSignIn", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.SupportSignInRequestBody Body;
        
        public SupportSignInRequest() {
        }
        
        public SupportSignInRequest(RDMConfig.AuthenticateService.SupportSignInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class SupportSignInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SupportSignInRequestBody() {
        }
        
        public SupportSignInRequestBody(string login_name, string password) {
            this.login_name = login_name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SupportSignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SupportSignInResponse", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.SupportSignInResponseBody Body;
        
        public SupportSignInResponse() {
        }
        
        public SupportSignInResponse(RDMConfig.AuthenticateService.SupportSignInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class SupportSignInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SupportSignInResult;
        
        public SupportSignInResponseBody() {
        }
        
        public SupportSignInResponseBody(string SupportSignInResult) {
            this.SupportSignInResult = SupportSignInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LinkSiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LinkSite", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.LinkSiteRequestBody Body;
        
        public LinkSiteRequest() {
        }
        
        public LinkSiteRequest(RDMConfig.AuthenticateService.LinkSiteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class LinkSiteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string site_id;
        
        public LinkSiteRequestBody() {
        }
        
        public LinkSiteRequestBody(string login_name, string password, string site_id) {
            this.login_name = login_name;
            this.password = password;
            this.site_id = site_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LinkSiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LinkSiteResponse", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMConfig.AuthenticateService.LinkSiteResponseBody Body;
        
        public LinkSiteResponse() {
        }
        
        public LinkSiteResponse(RDMConfig.AuthenticateService.LinkSiteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class LinkSiteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LinkSiteResult;
        
        public LinkSiteResponseBody() {
        }
        
        public LinkSiteResponseBody(string LinkSiteResult) {
            this.LinkSiteResult = LinkSiteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface authenticate_ServicesSoapChannel : RDMConfig.AuthenticateService.authenticate_ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class authenticate_ServicesSoapClient : System.ServiceModel.ClientBase<RDMConfig.AuthenticateService.authenticate_ServicesSoap>, RDMConfig.AuthenticateService.authenticate_ServicesSoap {
        
        public authenticate_ServicesSoapClient() {
        }
        
        public authenticate_ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public authenticate_ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authenticate_ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authenticate_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDMConfig.AuthenticateService.SignInResponse RDMConfig.AuthenticateService.authenticate_ServicesSoap.SignIn(RDMConfig.AuthenticateService.SignInRequest request) {
            return base.Channel.SignIn(request);
        }
        
        public void SignIn(string login_name, string password) {
            RDMConfig.AuthenticateService.SignInRequest inValue = new RDMConfig.AuthenticateService.SignInRequest();
            inValue.Body = new RDMConfig.AuthenticateService.SignInRequestBody();
            inValue.Body.login_name = login_name;
            inValue.Body.password = password;
            RDMConfig.AuthenticateService.SignInResponse retVal = ((RDMConfig.AuthenticateService.authenticate_ServicesSoap)(this)).SignIn(inValue);
        }
        
        public void SSO() {
            base.Channel.SSO();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDMConfig.AuthenticateService.ADLookupResponse RDMConfig.AuthenticateService.authenticate_ServicesSoap.ADLookup(RDMConfig.AuthenticateService.ADLookupRequest request) {
            return base.Channel.ADLookup(request);
        }
        
        public void ADLookup(string email) {
            RDMConfig.AuthenticateService.ADLookupRequest inValue = new RDMConfig.AuthenticateService.ADLookupRequest();
            inValue.Body = new RDMConfig.AuthenticateService.ADLookupRequestBody();
            inValue.Body.email = email;
            RDMConfig.AuthenticateService.ADLookupResponse retVal = ((RDMConfig.AuthenticateService.authenticate_ServicesSoap)(this)).ADLookup(inValue);
        }
        
        public void SignOut() {
            base.Channel.SignOut();
        }
        
        public void BrowserClosed() {
            base.Channel.BrowserClosed();
        }
        
        public void KeepSessionAlive() {
            base.Channel.KeepSessionAlive();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDMConfig.AuthenticateService.TemporaryPasswordResponse RDMConfig.AuthenticateService.authenticate_ServicesSoap.TemporaryPassword(RDMConfig.AuthenticateService.TemporaryPasswordRequest request) {
            return base.Channel.TemporaryPassword(request);
        }
        
        public void TemporaryPassword(string login_name) {
            RDMConfig.AuthenticateService.TemporaryPasswordRequest inValue = new RDMConfig.AuthenticateService.TemporaryPasswordRequest();
            inValue.Body = new RDMConfig.AuthenticateService.TemporaryPasswordRequestBody();
            inValue.Body.login_name = login_name;
            RDMConfig.AuthenticateService.TemporaryPasswordResponse retVal = ((RDMConfig.AuthenticateService.authenticate_ServicesSoap)(this)).TemporaryPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDMConfig.AuthenticateService.UpdatePasswordResponse RDMConfig.AuthenticateService.authenticate_ServicesSoap.UpdatePassword(RDMConfig.AuthenticateService.UpdatePasswordRequest request) {
            return base.Channel.UpdatePassword(request);
        }
        
        public void UpdatePassword(string user_id, string password) {
            RDMConfig.AuthenticateService.UpdatePasswordRequest inValue = new RDMConfig.AuthenticateService.UpdatePasswordRequest();
            inValue.Body = new RDMConfig.AuthenticateService.UpdatePasswordRequestBody();
            inValue.Body.user_id = user_id;
            inValue.Body.password = password;
            RDMConfig.AuthenticateService.UpdatePasswordResponse retVal = ((RDMConfig.AuthenticateService.authenticate_ServicesSoap)(this)).UpdatePassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDMConfig.AuthenticateService.SupportSignInResponse RDMConfig.AuthenticateService.authenticate_ServicesSoap.SupportSignIn(RDMConfig.AuthenticateService.SupportSignInRequest request) {
            return base.Channel.SupportSignIn(request);
        }
        
        public string SupportSignIn(string login_name, string password) {
            RDMConfig.AuthenticateService.SupportSignInRequest inValue = new RDMConfig.AuthenticateService.SupportSignInRequest();
            inValue.Body = new RDMConfig.AuthenticateService.SupportSignInRequestBody();
            inValue.Body.login_name = login_name;
            inValue.Body.password = password;
            RDMConfig.AuthenticateService.SupportSignInResponse retVal = ((RDMConfig.AuthenticateService.authenticate_ServicesSoap)(this)).SupportSignIn(inValue);
            return retVal.Body.SupportSignInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDMConfig.AuthenticateService.LinkSiteResponse RDMConfig.AuthenticateService.authenticate_ServicesSoap.LinkSite(RDMConfig.AuthenticateService.LinkSiteRequest request) {
            return base.Channel.LinkSite(request);
        }
        
        public string LinkSite(string login_name, string password, string site_id) {
            RDMConfig.AuthenticateService.LinkSiteRequest inValue = new RDMConfig.AuthenticateService.LinkSiteRequest();
            inValue.Body = new RDMConfig.AuthenticateService.LinkSiteRequestBody();
            inValue.Body.login_name = login_name;
            inValue.Body.password = password;
            inValue.Body.site_id = site_id;
            RDMConfig.AuthenticateService.LinkSiteResponse retVal = ((RDMConfig.AuthenticateService.authenticate_ServicesSoap)(this)).LinkSite(inValue);
            return retVal.Body.LinkSiteResult;
        }
    }
}
