//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDMLink.RDM_Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://throwdownplanner.com/", ConfigurationName="RDM_Services.import_export_ServicesSoap")]
    public interface import_export_ServicesSoap {
        
        // CODEGEN: Generating message contract since element name site_id from namespace http://throwdownplanner.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://throwdownplanner.com/FileUpload", ReplyAction="*")]
        RDMLink.RDM_Services.FileUploadResponse FileUpload(RDMLink.RDM_Services.FileUploadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileUpload", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMLink.RDM_Services.FileUploadRequestBody Body;
        
        public FileUploadRequest() {
        }
        
        public FileUploadRequest(RDMLink.RDM_Services.FileUploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class FileUploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string site_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] f;
        
        public FileUploadRequestBody() {
        }
        
        public FileUploadRequestBody(string site_id, string fileName, byte[] f) {
            this.site_id = site_id;
            this.fileName = fileName;
            this.f = f;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileUploadResponse", Namespace="http://throwdownplanner.com/", Order=0)]
        public RDMLink.RDM_Services.FileUploadResponseBody Body;
        
        public FileUploadResponse() {
        }
        
        public FileUploadResponse(RDMLink.RDM_Services.FileUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://throwdownplanner.com/")]
    public partial class FileUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FileUploadResult;
        
        public FileUploadResponseBody() {
        }
        
        public FileUploadResponseBody(string FileUploadResult) {
            this.FileUploadResult = FileUploadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface import_export_ServicesSoapChannel : RDMLink.RDM_Services.import_export_ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class import_export_ServicesSoapClient : System.ServiceModel.ClientBase<RDMLink.RDM_Services.import_export_ServicesSoap>, RDMLink.RDM_Services.import_export_ServicesSoap {
        
        public import_export_ServicesSoapClient() {
        }
        
        public import_export_ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public import_export_ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public import_export_ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public import_export_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RDMLink.RDM_Services.FileUploadResponse RDMLink.RDM_Services.import_export_ServicesSoap.FileUpload(RDMLink.RDM_Services.FileUploadRequest request) {
            return base.Channel.FileUpload(request);
        }
        
        public string FileUpload(string site_id, string fileName, byte[] f) {
            RDMLink.RDM_Services.FileUploadRequest inValue = new RDMLink.RDM_Services.FileUploadRequest();
            inValue.Body = new RDMLink.RDM_Services.FileUploadRequestBody();
            inValue.Body.site_id = site_id;
            inValue.Body.fileName = fileName;
            inValue.Body.f = f;
            RDMLink.RDM_Services.FileUploadResponse retVal = ((RDMLink.RDM_Services.import_export_ServicesSoap)(this)).FileUpload(inValue);
            return retVal.Body.FileUploadResult;
        }
    }
}
